services:
    strapi:
        build:
            context: ./strapi
            dockerfile: ../docker/strapi/Dockerfile.dev
        ports:
            - "1337:1337"
        healthcheck:
            test: [ "CMD", "wget", "-qO-", "http://localhost:1337/admin" ]
            interval: 5s
            timeout: 2s
            retries: 30
        env_file:
            - .env
        environment:
            - NODE_ENV=development

    nextjs:
        build:
            context: ./nextjs
            dockerfile: ../docker/nextjs/Dockerfile.dev
        ports:
            - "3000:3000"
        healthcheck:
            test: [ "CMD", "wget", "-qO-", "http://localhost:3000" ]
            interval: 5s
            timeout: 2s
            retries: 20
        env_file:
            - .env
        environment:
            - NODE_ENV=development

    tests:
        image: mcr.microsoft.com/playwright:v1.56.1-noble
        depends_on:
            nextjs:
                condition: service_healthy
            strapi:
                condition: service_healthy
        working_dir: /tests
        volumes:
            - ./nextjs/tests:/tests/tests
            - ./nextjs/playwright.config.ts:/tests/playwright.config.ts
            - ./nextjs/package.json:/tests/package.json
            - ./nextjs/yarn.lock:/tests/yarn.lock
        environment:
            PLAYWRIGHT_BASE_URL: http://nextjs:3000
        command: >
            sh -c "
              corepack enable &&
              corepack prepare yarn@4.11.0 --activate &&
              yarn install --immutable &&
              npx playwright test --config=/tests/playwright.config.ts
            "
