services:
    strapi:
        image: gabgabb/portefolio-strapi:latest
        restart: always
        ports:
            - '1337:1337'
        volumes:
            - ./strapi:/app
        environment:
            - NODE_ENV=${NODE_ENV}
            - DATABASE_CLIENT=sqlite
            - DATABASE_FILENAME=./data/data.db
        env_file:
            - .env

    nextjs:
        image: gabgabb/portefolio-nextjs:latest
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./nextjs:/app
        environment:
            - NODE_ENV=${NODE_ENV}
        env_file:
            - .env

volumes:
    nextjs_cache:
