services:
    strapi:
        build:
            context: ./strapi
            dockerfile: ../docker/strapi/Dockerfile.dev
        ports:
            - "1337:1337"

    nextjs:
        build:
            context: ./nextjs
            dockerfile: ../docker/nextjs/Dockerfile.dev
        ports:
            - "3000:3000"

    tests:
        image: mcr.microsoft.com/playwright:v1.50.0-noble
        depends_on:
            nextjs:
                condition: service_started
            strapi:
                condition: service_started
        volumes:
            - ./nextjs:/tests
        working_dir: /tests
        command: >
            sh -c "
              corepack enable &&
              corepack prepare yarn@4.11.0 --activate &&
              yarn install --immutable &&
              npx playwright test --config=playwright.config.ts
            "
