services:
    strapi:
        build:
            context: ./strapi
            dockerfile: ../docker/strapi/Dockerfile.dev
        ports:
            - "1337:1337"

    nextjs:
        build:
            context: ./nextjs
            dockerfile: ../docker/nextjs/Dockerfile.dev
        ports:
            - "3000:3000"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
            interval: 5s
            timeout: 2s
            retries: 20

    tests:
        image: mcr.microsoft.com/playwright:v1.56.1-noble
        depends_on:
            nextjs:
                condition: service_healthy
            strapi:
                condition: service_started
        working_dir: /tests
        volumes:
            - ./nextjs:/tests
        environment:
            PLAYWRIGHT_BASE_URL: http://nextjs:3000
        command: >
            sh -c "
              corepack enable &&
              corepack prepare yarn@4.11.0 --activate &&
              yarn install --immutable &&
              npx playwright test --config=playwright.config.ts
            "
