services:
    strapi:
        build:
            context: ./strapi
            dockerfile: ../docker/strapi/Dockerfile.dev
        ports:
            - "1337:1337"

    nextjs:
        build:
            context: ./nextjs
            dockerfile: ../docker/nextjs/Dockerfile.dev
        ports:
            - "3000:3000"

    tests:
        image: mcr.microsoft.com/playwright:v1.56.1-noble
        network_mode: "service:nextjs"
        depends_on:
            nextjs:
                condition: service_started
            strapi:
                condition: service_started
        working_dir: /tests
        volumes:
            - ./nextjs:/tests
        environment:
            # 👇 dans ce mode, localhost:3000 = Next.js
            PLAYWRIGHT_BASE_URL: http://localhost:3000
        command: >
            sh -c "
              corepack enable &&
              corepack prepare yarn@4.11.0 --activate &&
              yarn install --immutable &&
              npx playwright test --config=playwright.config.ts
            "
