services:
  strapi:
    image: gabgabb/portefolio-strapi:latest
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development

  nextjs:
    image: gabgabb/portefolio-nextjs:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development